site_name: PyCharm Documentation for COMP1510
site_url: https://sitename.example
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: green
      accent: light green

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: green
      accent: light green
  features:
      - navigation.footer
nav:
  - Home: index.md
  - Disabling AI: Disabling_AI.md
  - Linking a Github Account: Linking_Github.md
  - Syncing Settings Across JetBrains IDEs: Syncing_IDE_Settings.md
  - Creating a New PyCharm Project: Create_Project.md
  - Glossary: glossary.md
  - Troubleshooting: troubleshooting.md
  
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
